banking/urls.py
from django.urls import path, register_converter
from . import views as bankingViews
from banking.converters import DateConverter


app_name = 'banking'
register_converter(DateConverter, 'date')

urlpatterns = [
    path('', bankingViews.DashboardView.as_view(), name='home'),
    path('dashboard/', bankingViews.DashboardView.as_view(), name='dashboard'),
    path('dashboard/transactions/<int:pk>/<str:month>/', bankingViews.DashboardTransactionsFilter.as_view(), name='dashboard_transactions'),
    path('accounts/', bankingViews.AccountListView.as_view(), name='account_list'),
    path('accounts/<int:pk>/detail', bankingViews.AccountDetailView.as_view(), name='account_detail'),
    path('accounts/create/', bankingViews.AccountCreateView.as_view(), name='account_create'),
    path('accounts/<int:pk>/update/', bankingViews.AccountUpdateView.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/', bankingViews.AccountDeleteView.as_view(), name='account_delete'),
    path('categories/', bankingViews.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/detail', bankingViews.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/create/<str:type>/', bankingViews.CategoryCreateView.as_view(), name='category_create'),
    path('categories/create/<str:type>/<int:nested_to_id>/', bankingViews.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/update/', bankingViews.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', bankingViews.CategoryDeleteView.as_view(), name='category_delete'),
    path('transactions/', bankingViews.TransactionListView.as_view(), name='transaction_list'),
    path('transactions/<int:pk>/detail', bankingViews.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/create/', bankingViews.TransactionCreateView.as_view(), name='transaction_create'),
    path('transactions/<int:pk>/update/', bankingViews.TransactionUpdateView.as_view(), name='transaction_update'),
    path('transactions/delete/<str:ids>/', bankingViews.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('transactions/internal_transfer/<str:transaction_ids>/', bankingViews.TransactionInternalTransferView.as_view(), name='transaction_internal_transfer'),
    path('transactions/categorize/<str:transaction_ids>/', bankingViews.TransactionCategorizeView.as_view(), name='transaction_categorize'),
    path('transactions/merge/<str:transaction_ids>/', bankingViews.TransactionMergeView.as_view(), name='transaction_merge'),
    path('transactions/import/', bankingViews.import_file, name='import_csv'),
    path('rules/', bankingViews.RuleListView.as_view(), name='rule_list'),
    path('rules/create/', bankingViews.RuleCreateView.as_view(), name='rule_create'),
    path('rules/<int:pk>/update/', bankingViews.RuleUpdateView.as_view(), name='rule_update'),
    path('rules/delete/<str:ids>/', bankingViews.RuleDeleteView.as_view(), name='rule_delete'),
    path('rules/<str:ids>/run/', bankingViews.RuleRunView.as_view(), name='rule_run'),
    path('rules/<str:ids>/test/', bankingViews.RuleTestView.as_view(), name='rule_test'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('banking.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

banking/models.py
import uuid
import banking.utils as utils 

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from emoji import EMOJI_DATA 
from datetime import datetime

class Bank(models.Model):
    name = models.CharField(max_length=100)
    logo = models.ImageField(upload_to="db-images/bank-logos/")
    country = models.CharField(max_length=100)

    def save(self, *args):
        if self.logo:
            self.logo.name = str(uuid.uuid4())
        super(Bank, self).save(*args)

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=3)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "currencies"


class Account(models.Model):
    ACCOUNT_TYPES = (
        ("checkingAccount", "Checking Account"),
        ("savingAccount", "Saving Account"),
        ("creditCard", "Credit Card"),
        ("investmentAccount", "Investment Account"),
        ("liabilityAccount", "Liability Account"),
    )

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=ACCOUNT_TYPES)
    closing_day = models.PositiveIntegerField(
        blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(28)]
    )
    due_day = models.PositiveIntegerField(
        blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(28)]
    )
    bank = models.ForeignKey(Bank, on_delete=models.RESTRICT)
    currency = models.ForeignKey(Currency, on_delete=models.RESTRICT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    incur_on_competency = models.BooleanField(default=True)

    class Meta:
        unique_together = ("user", "name")

    def __str__(self):
        return f"{self.name} ({dict(self.ACCOUNT_TYPES)[self.type]})"

    def getBalance(self):
        return sum([item.value for item in Transaction.objects.filter(account=self)])

    def getNotClassifiedTransactions(self):
        return Transaction.objects.filter(
            account=self, category=None, is_transfer=False
        )

    def getNotConciliedTransactions(self):
        return Transaction.objects.filter(account=self, concilied=False)


class Category(models.Model):
    CATEGORY_TYPE = (
        ("D", "Debit"),
        ("C", "Credit"),
    )

    name = models.CharField(max_length=100)
    type = models.CharField(max_length=1, choices=CATEGORY_TYPE)
    sorting = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nested_to = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True
    )

    def __str__(self):
        return f"{self.name} ({self.type})"

    class Meta:
        verbose_name_plural = "categories"

    def beginsWithEmoji(self):
        return self.name[:1] in EMOJI_DATA

    def getLastSort(nested_to, user):
        last_sort = Category.objects.filter(nested_to=nested_to, user=user).aggregate(
            last_sort=models.Max("sorting", output_field=models.IntegerField())
        )["last_sort"]
        if last_sort == None:
            last_sort = 0
        else:
            last_sort = last_sort + 1
        return last_sort

    def getNumberOfTransactions(self):
        category_and_parents_ids = [self.id]
        for subcategory in Category.objects.filter(nested_to__id=self.id):
            category_and_parents_ids.append(subcategory.id)
            for subsubcategory in Category.objects.filter(nested_to__id=subcategory.id):
                category_and_parents_ids.append(subsubcategory.id)
        transactions = Transaction.objects.filter(category__id__in=category_and_parents_ids).count()
        return transactions

    def getIncurredValueOfTransactions(self):
        category_and_parents_ids = [self.id]
        for subcategory in Category.objects.filter(nested_to__id=self.id):
            category_and_parents_ids.append(subcategory.id)
            for subsubcategory in Category.objects.filter(nested_to__id=subcategory.id):
                category_and_parents_ids.append(subsubcategory.id)
        transactions = Transaction.objects.filter(category__id__in=category_and_parents_ids)
        value = 0
        for transaction in transactions:
            value += transaction.value.__abs__()
        return value


    def getSubcategories(self):
        categories = Category.objects.filter(nested_to=self).order_by("type","sorting")
        return categories

    def getUserGroupedAndSortedCategories(user: User):
        listOfUserCreditCategories = list()
        listOfUserDebitCategories = list()
        qs = Category.objects.filter(user=user, nested_to=None).order_by(
            "type", "sorting"
        )
        for item in qs.iterator():
            if item.type == "C":
                listOfUserCreditCategories.append(
                    (
                        item.id,
                        {
                            "id": item.id,
                            "name": item.name,
                            "type": item.type,
                            "sorting": item.sorting,
                            "nested_to_id": item.nested_to.id
                            if item.nested_to != None
                            else None,
                            "level": "1",
                        },
                    )
                )
                for item2 in item.getSubcategories():
                    listOfUserCreditCategories.append(
                        (
                            item2.id,
                            {
                                "id": item2.id,
                                "name": item2.name,
                                "type": item2.type,
                                "sorting": item2.sorting,
                                "nested_to_id": item2.nested_to.id
                                if item2.nested_to != None
                                else None,
                                "level": "2",
                            },
                        )
                    )
                    for item3 in item2.getSubcategories():
                        listOfUserCreditCategories.append(
                            (
                                item3.id,
                                {
                                    "id": item3.id,
                                    "name": item3.name,
                                    "type": item3.type,
                                    "sorting": item3.sorting,
                                    "nested_to_id": item3.nested_to.id
                                    if item3.nested_to != None
                                    else None,
                                    "level": "3",
                                },
                            )
                        )
            else:
                listOfUserDebitCategories.append(
                    (
                        item.id,
                        {
                            "id": item.id,
                            "name": item.name,
                            "type": item.type,
                            "sorting": item.sorting,
                            "nested_to_id": item.nested_to.id
                            if item.nested_to != None
                            else None,
                            "level": "1",
                        },
                    )
                )
                for item2 in item.getSubcategories():
                    listOfUserDebitCategories.append(
                        (
                            item2.id,
                            {
                                "id": item2.id,
                                "name": item2.name,
                                "type": item2.type,
                                "sorting": item2.sorting,
                                "nested_to_id": item2.nested_to.id
                                if item2.nested_to != None
                                else None,
                                "level": "2",
                            },
                        )
                    )
                    for item3 in item2.getSubcategories():
                        listOfUserDebitCategories.append(
                            (
                                item3.id,
                                {
                                    "id": item3.id,
                                    "name": item3.name,
                                    "type": item3.type,
                                    "sorting": item3.sorting,
                                    "nested_to_id": item3.nested_to.id
                                    if item3.nested_to != None
                                    else None,
                                    "level": "3",
                                },
                            )
                        )
        listOfUserCategories = (
            ("","No category"),
            ("Credit Categories",
            listOfUserCreditCategories),
            ("Debit Categories",
            listOfUserDebitCategories)
        )
        return listOfUserCategories


class Transaction(models.Model):
    incurBudgetDateTypes = (
        ("", "Account Default"),
        ("C", "Competency Date"),
        ("T", "Transaction Date")
    )

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    date = models.DateField()
    competency_date = models.DateField(blank=True, null=True)
    description = models.CharField(max_length=200)
    merged_to = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True
    )
    is_transfer = models.BooleanField(default=False)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )

templates/banking/account_detail.html
{% load i18n %}
<div class="modal-header">
  <h5 class="modal-title">{% trans "Account Details" %}</h5>
  <button type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"></button>
</div>
<div class="modal-body">
  <div class="datagrid">
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Account Name" %}</div>
      <div class="datagrid-content">{{ account.name }}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Bank Name" %}</div>
      <div class="datagrid-content">
        <img src="{{ media_url }}{{ account.bank.logo.url }}"
             width="24"
             height="24"
             alt="Bank Logo" />
        <span class="p-2">{{ account.bank.name }}</span>
      </div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Account Type" %}</div>
      <div class="datagrid-content">{% trans account.get_type_display %}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Currency" %}</div>
      <div class="datagrid-content">
        <span class="flag flag-xs flag-country-{{ account.currency.code|slice:2|lower }} me-2"></span>
        {{ account.currency }} ({{ account.currency.code }})
      </div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Closing Day" %}</div>
      <div class="datagrid-content">{{ account.closing_day }}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Due Day" %}</div>
      <div class="datagrid-content">{{ account.due_day }}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Transactions without Classification" %}</div>
      <div class="datagrid-content">{{ account.getNotClassifiedTransactions.count }}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Transactions not Concilied" %}</div>
      <div class="datagrid-content">{{ account.getNotConciliedTransactions.count }}</div>
    </div>
    <div class="datagrid-item">
      <div class="datagrid-title">{% trans "Account Balance" %}</div>
      <div class="datagrid-content">{{ account.getBalance }}</div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <a href="#" class="btn btn-link link-secondary" data-bs-dismiss="modal">{% trans "Close" %}</a>
  <a href="{% url "banking:account_statement" account.id %}"
     class="btn btn-primary ms-auto"
     data-bs-dismiss="modal">
    <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
    <svg xmlns="http://www.w3.org/2000/svg"
         class="icon"
         width="24"
         height="24"
         viewBox="0 0 24 24"
         stroke-width="2"
         stroke="currentColor"
         fill="none"
         stroke-linecap="round"
         stroke-linejoin="round">
      <path stroke="none" d="M0 0h24v24H0z" fill="none" />
      <path d="M12 5l0 14" />
      <path d="M5 12l14 0" />
    </svg>
    {% trans "Open Statement" %}
  </a>
</div>

templates/banking/account_list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <!-- Page pre-title -->
          <div class="page-pretitle">Overview</div>
          <h2 class="page-title">{% trans "Accounts" %}</h2>
        </div>
        <div class="col-auto ms-auto d-print-none">
          <div class="btn-list">
            <a href="#"
               class="btn btn-primary d-none d-sm-inline-block modal-button"
               data-form-url="{% url 'banking:account_create' %}"
               data-bs-toggle="modal"
               data-bs-target="#modals-here"
               id="add_button">
              <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
              <svg xmlns="http://www.w3.org/2000/svg"
                   class="icon"
                   width="24"
                   height="24"
                   viewBox="0 0 24 24"
                   stroke-width="2"
                   stroke="currentColor"
                   fill="none"
                   stroke-linecap="round"
                   stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M12 5l0 14"></path>
                <path d="M5 12l14 0"></path>
              </svg>
              {% trans "Create new account" %}
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-header">{% trans "List of Accounts" %}</div>
            <div class="table-responsive">
              <table class="table card-table table-vcenter text-nowrap datatable">
                <thead>
                  <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th>{% trans "Currency" %}</th>
                    <th>{% trans "Closing Day" %}</th>
                    <th>{% trans "Due Day" %}</th>
                    <th class="text-end">{% trans "Balance" %}</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for account_type, account_balance in accounts_balances.items %}
                  {% for account in account_list %}
                  {% if account.type == account_type %}
                    <tr>
                      <td>
                        <a href="{% url 'banking:transaction_list' %}?account_id={{ account.id }}">
                          <img src="{{ media_url }}{{ account.bank.logo.url }}"
                               width="32"
                               height="32"
                               alt="Bank Logo" />
                          <span class="px-2">{{ account.name }}</span>
                        </a>
                        {% if account.getNotClassifiedTransactions.count > 0 %}
                          <a href="{% url 'banking:transaction_list' %}?account_id={{ account.id }}&amp;not_classified=1">
                            <span class="badge badge-pill bg-red text-white mb-3"
                                data-bs-toggle="tooltip"
                                data-bs-placement="top"
                                title="{% trans "Transactions not classified" %}">{{ account.getNotClassifiedTransactions.count }}
                              </span>
                            </a>
                        {% endif %}
                        {% if account.getNotConciliedTransactions.count > 0 %}
                        <a href="{% url 'banking:transaction_list' %}?account_id={{ account.id }}&amp;not_concilied=1">
                          <span class="badge badge-pill bg-yellow text-white mb-3"
                                data-bs-toggle="tooltip"
                                data-bs-placement="top"
                                title="{% trans "Transactions not concilied" %}">{{ account.getNotConciliedTransactions.count }}
                              </span>
                            </a>
                        {% endif %}
                      </td>
                      <td>{% trans account.get_type_display %}</td>
                      <td>
                        <span class="flag flag-xs flag-country-{{ account.currency.code|slice:2|lower }} me-2"></span>
                        {{ account.currency }} ({{ account.currency.code }})
                      </td>
                      <td class="text-center">{% if account.closing_day %}{{ account.closing_day }}{% else %}-{% endif %}</td>
                      <td class="text-center">{% if account.due_day %}{{ account.due_day }}{% else %}-{% endif %}</td>
                      <td class="text-end">{{ account.getBalance }}</td>
                      <td class="text-end">
                        <button class="btn align-text-top btn-danger modal-button"
                                data-bs-toggle="modal"
                                data-bs-target="#modals-here"
                                data-form-url="{% url 'banking:account_delete' account.id %}"
                                data-form-delete="True">
                          <svg xmlns="http://www.w3.org/2000/svg"
                               class="icon icon-tabler icon-tabler-trash"
                               width="24"
                               height="24"
                               viewBox="0 0 24 24"
                               stroke-width="2"
                               stroke="currentColor"
                               fill="none"
                               stroke-linecap="round"
                               stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M4 7l16 0" />
                            <path d="M10 11l0 6" />
                            <path d="M14 11l0 6" />
                            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                          </svg>
                          {% trans "Delete" %}
                        </button>
                        <button class="btn align-text-top btn-success modal-button"
                                data-bs-toggle="modal"
                                data-bs-target="#modals-here"
                                data-form-url="{% url 'banking:account_update' account.id %}">
                          <svg xmlns="http://www.w3.org/2000/svg"
                               class="icon icon-tabler icon-tabler-edit"
                               width="24"
                               height="24"
                               viewBox="0 0 24 24"
                               stroke-width="2"
                               stroke="currentColor"
                               fill="none"
                               stroke-linecap="round"
                               stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                            <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                            <path d="M16 5l3 3" />
                          </svg>
                          {% trans "Edit" %}
                        </button>
                      </td>
                    </tr>
                  {% endif %}
                  {% endfor %}
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>
                      {% for type_name, type_display_name in accounts_types %}
                        {% if type_name == account_type %}
                          {{ type_display_name }}
                        {% endif %}
                      {% endfor %}
                    </th>
                    <th class="text-end">{{ account_balance }}</th>
                    <th></th>
                  </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>{% trans "Total" %}</th>
                  <th class="text-end">{{ total_balance }}</th>
                  <th></th>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block extrascripts %}
<script>
  document.addEventListener('DOMContentLoaded', (e) => {
    var modalButtons = document.getElementsByClassName("modal-button");
    for (var index=0; index < modalButtons.length; index++) {
      modalForm(modalButtons[index], {
        formURL: modalButtons[index]["dataset"]["formUrl"],
        modalID: "#modals-here",
        isDeleteForm: (modalButtons[index]["dataset"]["formDelete"] == true),
      });
    }
  });
</script>
{% endblock extrascripts %}

templates/banking/category_detail.html
{% load i18n %}
{% load static %}
{% block content %}
    <div class="modal-header">
      <h5 class="modal-title">{% trans "Category Details" %}</h5>
      <button type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div class="datagrid">
        <div class="datagrid-item">
          <div class="datagrid-title">{% trans "Category Name" %}</div>
          <div class="datagrid-content">{{ category.name }}</div>
        </div>
        <div class="datagrid-item">
          <div class="datagrid-title">{% trans "Category Path" %}</div>
          <div class="datagrid-content">
            <ol class="breadcrumb" aria-label="breadcrumbs">
              <li class="breadcrumb-item">{% trans category.get_type_display|add:' Category' %}</li>
              {% if category.nested_to %}
                {% if category.nested_to.nested_to %}
                  <li class="breadcrumb-item">{{ category.nested_to.nested_to.name }}</li>
                {% endif %}
              {% endif %}
              {% if category.nested_to %}<li class="breadcrumb-item">{{ category.nested_to.name }}</li>{% endif %}
            </ol>
          </div>
        </div>
        <div class="datagrid-item">
          <div class="datagrid-title">{% trans "Subcategories" %}</div>
          <div class="datagrid-content"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-9 col-xl-10 order-2 order-sm-1 mt-3">
          <div id="sortablelist" class="list-group mb-4 mt-3" data-id="1">
            {% for item in category.getSubcategories %}
              <div class="p-2 list-group-item d-flex align-items-center justify-content-between"
                   data-id="2">
                <svg xmlns="http://www.w3.org/2000/svg"
                     class="icon icon-tabler icon-tabler-grip-horizontal"
                     width="24"
                     height="24"
                     viewBox="0 0 24 24"
                     stroke-width="2"
                     stroke="currentColor"
                     fill="none"
                     stroke-linecap="round"
                     stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <path d="M5 9m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                  <path d="M5 15m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                  <path d="M12 9m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                  <path d="M12 15m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                  <path d="M19 9m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                  <path d="M19 15m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                </svg>
                {{ item.name }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-link link-secondary" data-bs-dismiss="modal">{% trans "Close" %}</a>
        <form>
          <button type="submit">teste</button>
          <script>
            alert('oi');
          </script>
          <a href="#"
          class="btn btn-success ms-auto modal-button"
          data-form-url="{% url "banking:account_update" category.id %}"
          data-form-delete="false">
          <svg xmlns="http://www.w3.org/2000/svg"
          class="icon icon-tabler icon-tabler-check"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          stroke-width="2"
          stroke="currentColor"
          fill="none"
          stroke-linecap="round"
          stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M5 12l5 5l10 -10" />
        </svg>
        {% trans "Edit Category" %}
      </a>
    </form>
        <script>
            new Sortable(sortablelist, {
                animation: 150,
                ghostClass: 'blue-background-class',
                onSort: function (/**Event*/evt) {
                  console.log(evt);
                }
            });
            
        </script>
        <script>
            var modalButtons = document.getElementsByClassName("modal-button");
            console.log(modalButtons);
            for (var index=0; index < modalButtons.length; index++) {
              modalForm(modalButtons[index], {
                formURL: modalButtons[index]["dataset"]["formUrl"],
                modalID: "#modals-here",
                isDeleteForm: modalButtons[index]["dataset"]["formDelete"],
                errorClass: '.is-invalid'
              });
            }
        </script>
      </div>
    </div>
{% endblock content %}